### ISSUE TITLE
수동 로그인 관련

### ISSUE THREAD

**Issue by ringnave** [sharebook-kr/kiwoom-version#1]
수동 로그인시 로그인이 안되어 아래와 같이 수정했더니 로그인됐습니다.

main.py 파일의 136번째줄
136: click_button(button)
137: click_button(button)

click_button(button) 을 한번 더 호출합니다.

**Comment by brayden-jo** [comment]
감사합니다. 구조를 조금 변경해봤습니다.

**Comment by brayden-jo** [comment]
구조 변경함.
