### ISSUE TITLE
실투자 로그인시에 문제. 도움 부탁 드림니다.

### ISSUE THREAD

**Issue by remon766** [sharebook-kr/kiwoom-version#4]
실투자 로그인시에 인증서번호까지 입력 된후 진행이 않됩니다. 마우스로 확인을 누르면 사진과 같은 메시지박스가 뜨고요.
마우스로 인증서부분 지우고 다시 입력후 확인 누르면 그제서야 로그인이 진행 되낸요
![캡처](https://user-images.githubusercontent.com/59525580/116775246-fa8b8600-aa9c-11eb-845c-3c0b6007c805.PNG)

**Comment by brayden-jo** [comment]
새로운 형태로 업데이트하였습니다.
