### ISSUE TITLE
작동이 안되어서 수정해 보았습니다.

### ISSUE THREAD

**Issue by robotjuhwan** [sharebook-kr/kiwoom-version#5]
run.bat 파일을 관리자권환된 cmd에서 실행하면 잘 되는데, run.bat 단독으로 관리권한 실행하니 작동을 안하네요.
제 컴퓨터는 실행한 위치를 알아오는데 오류가 있는 듯 합니다. 안되시는 분들은 참고하세요.
------------------------------------------------------------------------------------------------------------
run.bat을 다음과 같이 수정하였습니다.

@echo off
cd %~dp0
D:/Users/Juhwan/Anaconda3/python N:/gitHub/kiwoom/kiwoom-version-master/version.py
D:/Users/Juhwan/Anaconda3/python N:/gitHub/kiwoom/kiwoom-version-master/auto_on.py
------------------------------------------------------------------------------------------------------------
auto_on.py 에서 다음과 같이 수정하였습니다.

CUR_PATH = os.getcwd() -> CUR_PATH = "N:/gitHub/kiwoom/kiwoom-version-master"
------------------------------------------------------------------------------------------------------------
version.py 에서 다음과 같이 수정하였습니다.

CUR_PATH = os.getcwd() -> CUR_PATH = "N:/gitHub/kiwoom/kiwoom-version-master"
f = open("user.txt") -> f = open("N:/gitHub/kiwoom/kiwoom-version-master/user.txt")
------------------------------------------------------------------------------------------------------------

여기서 D:/Users/Juhwan/Anaconda3/python와 N:/gitHub/kiwoom/kiwoom-version-master 값은 제 컴퓨터 기준값이고, 사용자 별로 알맞은 값을 사용하시면 됩니다.

**Comment by remon766** [comment]
이제 봤습니다.감사합니다.
